### ISSUE TITLE
运行Utils.py时总是有这个问题

### ISSUE THREAD

**Issue by qyge** [WuJie1010/Facial-Expression-Recognition.Pytorch#1]
Traceback (most recent call last):
  File "D:/Facial-Expression-Recognition.Pytorch/mainpro_FER.py", line 15, in <module>
    import utils
  File "D:\Facial-Expression-Recognition.Pytorch\utils.py", line 16, in <module>
    _, term_width = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by WuJie1010** [comment]
This could be a issue of python version.
Maybe you can change the code to: 
```
# _, term_width = os.popen('stty size', 'r').read().split() (remove)
term_width = 80 (set the term_width to 80 directly)
```

**Comment by lander1003** [comment]
term_width = 80 (set the term_width to 80 directly)
                           ^
SyntaxError: invalid syntax

缩进错误咋搞啊

**Comment by victor-mageto** [comment]
@lander1003 did you solve this error. If so what is the solution

**Comment by victor-mageto** [comment]
@lander1003  `term_width=80 #(set the term_)`

**Comment by victor-mageto** [comment]
@lander1003 `term_width=80  #(set the term_width to 80 directly)`

**Comment by yangsenchen** [comment]
666

**Comment by RizwanShaukat936** [comment]
> ```
> term_width = 80 (set the term_width to 80 directly)
>                        ^
> ```
> 
> SyntaxError: invalid syntax
> 
> 缩进错误咋搞啊

You should write only 
`term_width= 80`
instead of 
`term_width = 80 (set the term_width to 80 directly)`
