### ISSUE TITLE
 _, term_width = os.popen('stty size', 'r').read().split()

### ISSUE THREAD

**Issue by kongzewuxin** [WuJie1010/Facial-Expression-Recognition.Pytorch#10]
when I run  mainpro_FER or mainpro_CK+, meet the follow error:
imports utils
 _, term_width = os.popen('stty size', 'r').read().split()
ValueError :not enough values to unpack (expected 2, get 0)

 I have found a lot of information, but there is still no solution.please help me!
(notes: I run in gtx900Ti +python3.5+torch0.4.1+torchivision0.2.1)
Thanks!!!

**Comment by WuJie1010** [comment]
May be you can refer to this: https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch/issues/1

**Comment by yucainiaoyu** [comment]
_, term_width = os.popen('stty size', 'r').read().split()（remove）
我加了之后显示NameError: name 'remove' is not defined

**Comment by Wtlovezy** [comment]
> 
> 
> _, term_width = os.popen('stty size', 'r').read().split()（remove）
> 我加了之后显示NameError: name 'remove' is not defined

term_width = 80  # (set the term_width to 80 directly)

**Comment by primaryer** [comment]
> _, term_width = os.popen('stty size', 'r').read().split()（remove）
> 我加了之后显示NameError: name 'remove' is not defined

哈哈哈,他是要你把上面一句注释掉,直接给term_width赋值80

**Comment by primaryer** [comment]
use command 'stty size' in the dir, and terminal will show the result.
set the term_width to the 2rd value directly.

**Comment by krisun1995** [comment]
把你微信或者qq发我一下，咸鱼不能发




------------------&nbsp;Original&nbsp;------------------
