### ISSUE TITLE
How to run on CPU?

### ISSUE THREAD

**Issue by rathishkumar** [WuJie1010/Facial-Expression-Recognition.Pytorch#101]
Getting below error on CPU machine:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on
a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by jinensetpal** [comment]
on vizualize.py:
- Comment each line of code that calls cuda [44 and 50]
- Replace `checkpoint = torch.load(os.path.join('FER2013_VGG19', 'PrivateTest_model.t7'), map_location=torch.device('cpu'))`

**Comment by jinensetpal** [comment]
created a PR detailing updated code to this effect
