### ISSUE TITLE
mainpro_CK+.py:27: in <module>     opt = parser.parse_args()

### ISSUE THREAD

**Issue by kongzewuxin** [WuJie1010/Facial-Expression-Recognition.Pytorch#11]
First of all, thank you for your reply to the previous question, it has been resolved.But I run the utils.py,next to have follow these quesion:
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/f404/kongzewuxin/Facial_Expression_Recognition_Pytorch, inifile: usage: _jb_pytest_runner.py [-h] [--model MODEL] [--dataset DATASET]
                            [--fold FOLD] [--bs BS] [--lr LR] [--resume]
_jb_pytest_runner.py: error: unrecognized arguments: /home/f404/kongzewuxin/Facial_Expression_Recognition_Pytorch/mainpro_CK+.py

mainpro_CK+.py:None (mainpro_CK+.py)
mainpro_CK+.py:27: in <module>
    opt = parser.parse_args()
../../anaconda3/lib/python3.5/argparse.py:1729: in parse_args
    self.error(msg % ' '.join(argv))
../../anaconda3/lib/python3.5/argparse.py:2385: in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
../../anaconda3/lib/python3.5/argparse.py:2372: in exit
    _sys.exit(status)
E   SystemExit: 2
collected 0 items / 1 errors
==================================== ERRORS ====================================
_______________________ ERROR collecting mainpro_CK+.py ________________________
mainpro_CK+.py:27: in <module>
    opt = parser.parse_args()
../../anaconda3/lib/python3.5/argparse.py:1729: in parse_args
    self.error(msg % ' '.join(argv))
../../anaconda3/lib/python3.5/argparse.py:2385: in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
../../anaconda3/lib/python3.5/argparse.py:2372: in exit
    _sys.exit(status)
E   SystemExit: 2
------------------------------- Captured stderr --------------------------------
usage: _jb_pytest_runner.py [-h] [--model MODEL] [--dataset DATASET]
                            [--fold FOLD] [--bs BS] [--lr LR] [--resume]
_jb_pytest_runner.py: error: unrecognized arguments: /home/f404/kongzewuxin/Facial_Expression_Recognition_Pytorch/mainpro_CK+.py
=========================== 1 error in 0.57 seconds ============================

I'm very sad, after look for losts information.
please help me reslove again
Thankyou.

**Comment by WuJie1010** [comment]
I haven't used pytest. Please use the following code in shell:
python mainpro_CK+.py --model VGG19 --bs 128 --lr 0.01 --fold 1

**Comment by kongzewuxin** [comment]
OK!!!
Thank you so much for your help!!!
