### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by liujiang137** [WuJie1010/Facial-Expression-Recognition.Pytorch#13]
I run 'python mainpro_FER.py --model VGG19 --bs 128 --lr 0.01',
but when 
train_loss += loss.data[0]
 [========== 225/225 ==========>] | Loss: 1.797 | Acc: 27.000% (7936/28709)  
RuntimeError: CUDA error: out of memory 
how to solve the problem,thanks for your help

**Comment by WuJie1010** [comment]
please check your GPU
