### ISSUE TITLE
Having problems in understanding the implement of 10-fold Cross validation ?

### ISSUE THREAD

**Issue by juneweng** [WuJie1010/Facial-Expression-Recognition.Pytorch#16]
Hi, WuJie！this is a great work! I am interested in tuning the model.

I am having problems while debugging "mainpro_CK+.py".
parser.add_argument('--fold', default=1, type=int, help='k fold number')

My questions:
1. fold default is 1,while I has not input,It turn to 10.I really want to know how to realize.
2. Could you please give me more detail about the implement of 10-fold Cross validation? 

Thank you in advance!

**Comment by WuJie1010** [comment]
please use "python k_fold_train.py"

**Comment by juneweng** [comment]
Thank you for your prompt!

there are my understands:for 1~9 fold , we count test number in order,for 10 fold,we count in the reverse order,In that way,we ignore some overlaps or discard some pictures,such as angry(135),we count 120,disgust (177) we count 180.But It doesn't matter.every time,we choose the fix test number,and the rest for train.Do I understand correctly?

Recently, I am stuck in data augment in CK+, your work help me a lot.Thank you once again.

**Comment by WuJie1010** [comment]
Yes

**Comment by juneweng** [comment]
Thank you！
