### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Okityou** [WuJie1010/Facial-Expression-Recognition.Pytorch#20]
### why I follw your steps and met this error and can you help me to solve it?
when I run "python visualize.py"
![1546337842 1](https://user-images.githubusercontent.com/44048634/50571994-cb43ac00-0df1-11e9-8f09-eedfb40dd930.png)

**Comment by WuJie1010** [comment]
you may should check your computer setting.  
I guess it's a computer setting problem.
