### ISSUE TITLE
Please help me! When run train(epoch)

### ISSUE THREAD

**Issue by Fuhongshuai** [WuJie1010/Facial-Expression-Recognition.Pytorch#21]
Epoch: 0
learning_rate: 0.01
Traceback (most recent call last):
  File "mainpro_FER.py", line 214, in <module>
    train(epoch)
  File "mainpro_FER.py", line 119, in train
    train_loss += loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by zxw1992** [comment]
Use 
`train_loss += loss.item()`
