### ISSUE TITLE
Error in running my own model

### ISSUE THREAD

**Issue by NomiMalik0207** [WuJie1010/Facial-Expression-Recognition.Pytorch#24]
when i run this training file on my own model i gives this error.
can you tell me why this happen?
Epoch: 0
learning_rate: 0.1
Traceback (most recent call last):
  File "mainpro_FER.py", line 229, in <module>
    train(epoch)
  File "mainpro_FER.py", line 132, in train
    utils.clip_gradient(optimizer, 0.1)
  File "/home/naveed/Facial-Expression-Recognition.Pytorch-master/utils.py", line 72, in clip_gradient
    param.grad.data.clamp_(-grad_clip, grad_clip)
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by WuJie1010** [comment]
may be your model has some layer don't update its gradient, you should check your code

**Comment by NomiMalik0207** [comment]
exactly

**Comment by NomiMalik0207** [comment]
Actually I have checked my model, and it is not upgrading gradients, but how I can solve this problem. When I print model summary it's normal.

**Comment by WuJie1010** [comment]
I have met this problem,  may be your model has defined some layer but is doesn't use, you should comment out these code。

**Comment by NomiMalik0207** [comment]
Sorry for disturbance, i have a question that in public and private test accuracies why you use outputs_avg?

**Comment by WuJie1010** [comment]
Because I use ten crops in the image, and I want to compute the average of outputs for the 10 crops.

**Comment by NomiMalik0207** [comment]
Actually in trasforms of test set you are applying lamda transform? Can i ask why you use 10 crops only for validation and test set? 
Sorry for disturbing you .

**Comment by WuJie1010** [comment]
In the training stage, I randomly cut 42*42 image to data augmentation.
During testing, I use 10 crops for a more convincing classification results. It like a voting mechanism,  the model have 10 image to select the best answer.

**Comment by NomiMalik0207** [comment]
when i use landmarks with images, and concatenate these image with landmarks . It gives dimension mismatch error. 
 landmark size (16,136) and emotion fc size (160,256). This 160 size is due to that 10 crops. How can i solve this problem.
Thank you for quick response

**Comment by WuJie1010** [comment]
Two alternative approaches：
1. you can repeat your landmark size to (160, 136) and concatenate with emotion fc_size.
2. you can reshape  emotion fc size (160,256). to (16,10,256) and concatenate .

**Comment by NomiMalik0207** [comment]
for the 1st approach, 16 is the batch size. so how can i change batch size 16 to 160 ?
for second approach i think it will give the error of expecting dimension which is for network and this 2nd approach have dimension 5.

**Comment by NomiMalik0207** [comment]
You said that you achieve stat of art accuracy 73.11%, but i saw in some papers they have claimed that they 75%. I have tried everything and could not get more that 74%.

**Comment by WuJie1010** [comment]
you can use "torch.repeat"  function
May be they use ensemble technique to achieve these performance.
