### ISSUE TITLE
fer2013训练好的模型

### ISSUE THREAD

**Issue by LeonardNiu** [WuJie1010/Facial-Expression-Recognition.Pytorch#26]
您好，由于自己的设备问题没办法实现对数据集fer2013的训练，请问您有最终达到70%左右准确率的参数文件吗？我想看一下最终效果，谢谢

**Comment by NomiMalik0207** [comment]
i think the same setting of parameters meet 70+% accuracy on VGG using FER2013. I have tested it. I do not know why you did not get it.
https://drive.google.com/open?id=1Oy_9YmpkSKX1Q8jkOhJbz3Mc7qjyISzU
you can found here the pre trained model and run visulize.py to check the results
