### ISSUE TITLE
out of memory in test

### ISSUE THREAD

**Issue by tangyuanhenyuan** [WuJie1010/Facial-Expression-Recognition.Pytorch#29]
Thanks a lot for your code!

I met a problem in PublicTest and PrivateTest. In this period, --bs 128 may be out of memory.
In training,the memory is 2600MiB /  8114MiB.

It is so strange that the big memory usage gap exists between test and train.

Looking forward to your reply

**Comment by WuJie1010** [comment]
I use tencrop, so the real batch size will be batch_size *10， please decrease the batch size
