### ISSUE TITLE
Why 44*44 input can be trained through VGG?

### ISSUE THREAD

**Issue by Weirdo233** [WuJie1010/Facial-Expression-Recognition.Pytorch#30]
Generally speaking, for VGG16 or 19, the input size is 224x224, 44x44 image should be too small to be convoluted for so many times. Why there's no problem in this project?

**Comment by WuJie1010** [comment]
In my opinion, VGG is used to extract the local feature and global feature of the image. 44*44 is suitable in the task.

**Comment by dagongji10** [comment]
@WuJie1010 so, have you changed the VGG-net ? If not, the output feature will be too small ?
