### ISSUE TITLE
Pre-trained VGG19 of CK+

### ISSUE THREAD

**Issue by phamvanlinh143** [WuJie1010/Facial-Expression-Recognition.Pytorch#32]
Could you provide pre-trained model of VGG16？(CK+ Dataset)

**Comment by WuJie1010** [comment]
we use cross validation in CK+ dataset, so it have 10  pre-trained model

**Comment by phamvanlinh143** [comment]
You can send them to my email, can't you. My email is phamvanlinh143@gmail.com. Thank you for your help.
