### ISSUE TITLE
关于预训模型

### ISSUE THREAD

**Issue by huahuahuaz** [WuJie1010/Facial-Expression-Recognition.Pytorch#33]
你好，首先非常感谢您的代码，请问可以提供一下预训模型吗，您给的谷歌盘链接需要翻墙才可以下载，本人邮箱737630678@qq.com，非常感谢

**Comment by nikee1** [comment]
你好，非常感谢您的分享，我想试着运行一下你的模型，但是预训练模型下载不了，能否请您发给我一份，非常感谢！邮箱：844935094@qq.com

**Comment by hanguangl** [comment]
你好，非常感谢您的分享，我想试着运行一下你的模型，但是下载不了，能否请您发给我一份，非常感谢！邮箱：1804646776@qq.com

**Comment by o0Roy** [comment]
你好，非常感谢您的分享，我想试着运行一下你的模型，但是下载不了，能否请您发给我一份，非常感谢！邮箱：shenmonlove@qq.com

**Comment by o0Roy** [comment]
你好，非常感谢您的分享，我想试着运行一下你的模型，但是下载不了，能否请您发给我一份，非常感谢！邮箱：shenmonlove@qq.com
@WuJie1010

**Comment by o0Roy** [comment]
我下下来了，各位需要自己拿链接：https://pan.baidu.com/s/1w2TAWzaqh8YvT-1I6rojAg  提取码：skg2

**Comment by tony2278** [comment]
然而，预训练模型并不准确~
