### ISSUE TITLE
关于fer2013模型准确率的问题

### ISSUE THREAD

**Issue by tiannfff** [WuJie1010/Facial-Expression-Recognition.Pytorch#34]
你好，我们按照readme步骤下载了训练好的模型(PrivateTest_model.t7)，但是没有找到叫FER2013_VGG19的文件夹，就自己建了一个，再把模型放进去。
<img width="619" alt="Screen Shot 2019-05-06 at 4 01 19 AM" src="https://user-images.githubusercontent.com/43361132/57199615-c8311600-6fb3-11e9-8807-73549fded65b.png">

安装了pytorch 0.4版本，我们按照步骤输了python mainpro_FER.py --model VGG19 --bs 128 --lr 0.01
这样跑出来准确率只有25%左右
<img width="728" alt="WechatIMG11522" src="https://user-images.githubusercontent.com/43361132/57199629-e7c83e80-6fb3-11e9-8afd-dc599316c2e9.png">

请问是我们训练好的模型放错地方了吗？可以帮忙看一下吗？谢谢！

**Comment by WuJie1010** [comment]
你应该直接test了，就不采用mainpro这个函数了，请参考函数plot_fer2013_confusion_matrix.py

**Comment by tiannfff** [comment]
> 你应该直接test了，就不采用mainpro这个函数了，请参考函数plot_fer2013_confusion_matrix.py

谢谢！如果我们要在这个pretrained model基础上再调整layer或者其他参数，用在新的10000张图片上（不是h5的格式），是不是这些图片都要跟原本一样处理，不用保存成h5吧？

**Comment by WuJie1010** [comment]
h5只是一个文件格式，只要能够载入即可
