### ISSUE TITLE
plot confusion matrix时被killed

### ISSUE THREAD

**Issue by zionward** [WuJie1010/Facial-Expression-Recognition.Pytorch#35]
我是cpu-only的电脑。
在跑confusion matrix那一步（python plot_fer2013_confusion_matrix.py --model VGG19 --split PrivateTest）的时候，先报了RuntimeError（torch.cuda.is_available() is False）。我按照报错提示
<img width="729" alt="WX20190505-155349@2x" src="https://user-images.githubusercontent.com/19849240/57200198-6be7db00-6f4e-11e9-927d-ae06dcaad1c2.png">
将plot_fer2013_confusion_matrix.py中的checkpoint = torch.load(os.path.join(path, opt.split + '_model.t7')) 改为👉checkpoint = torch.load(os.path.join(path, opt.split + '_model.t7'), map_location='cpu')
然后按照之前issues的那样comment掉了.cuda()的code。
然后再run plotting confusion matrix的指令的时候并没有报错，但是会卡死，然后最后显示killed
<img width="726" alt="WX20190505-155400@2x" src="https://user-images.githubusercontent.com/19849240/57200214-c5e8a080-6f4e-11e9-82b0-b40df7f9d412.png">

可以帮忙看一下是什么问题吗？谢谢！

**Comment by WuJie1010** [comment]
因为是因为一下子通过网络的参数量太大，cpu内存不够了，考虑在测试的时候调低batchsize尝试下。

**Comment by zionward** [comment]
哦，好的！谢谢！
