### ISSUE TITLE
关于在原程序上的修改

### ISSUE THREAD

**Issue by wangyijun6** [WuJie1010/Facial-Expression-Recognition.Pytorch#36]
作者你好！我想在您的原来visualize.py代码的基础上改为使用resnet模型，我在之前的issue中保存了您分享的一份resnet模型，想请问一下您分享的模型是基于哪个数据集训练的？以及想问问是否将代码net = VGG('VGG19')改为net = ResNet('Resnet18')，并且将checkpoint中的模型替换就可以了？resnet模型所在的文件夹名字有讲究吗？

不好意思我的问题有点多，非常感谢您！（如果方便的话，请问可以使用邮箱交流吗，我的邮箱是740063957@qq.com）

**Comment by wangyijun6** [comment]
作者你好！我发现了是改为ResNet18()，请问这样对吗？不过我改完之后得到的结果非常不准。
此外，我还根据您的代码，写了一份利用笔记本摄像头实时识别的代码，不知您是否也写过这样的程序，想和您探讨一下其中的问题。

非常感谢！

**Comment by wangyijun6** [comment]
作者你好，我想请问一下visualize.py是否只能检测只有一个人脸的图片？

**Comment by WuJie1010** [comment]
visualize.py是否只能检测只有一个人脸的图片,需要把人脸提前剪裁好

**Comment by wangyijun6** [comment]
> visualize.py是否只能检测只有一个人脸的图片,需要把人脸提前剪裁好

十分感谢！请问是如果一张照片里有许多人脸，将每一张人脸都剪裁为48x48，然后再去识别是吗？

**Comment by wangyijun6** [comment]
作者你好，想请问一下为什么CK+数据集不需要做process呀

**Comment by wangyijun6** [comment]
我已经知道答案了哈哈，感谢作者

**Comment by wangyijun6** [comment]
作者你好，请问有哪里可以看到您的模型网络结构图吗？

**Comment by wangyijun6** [comment]
感觉单看代码，不是很能理解整个网络的结构如何。谢谢！

**Comment by WuJie1010** [comment]
请看VGG的结构解析
