### ISSUE TITLE
关于fer2013的tencrop

### ISSUE THREAD

**Issue by juneweng** [WuJie1010/Facial-Expression-Recognition.Pytorch#38]
您好,在mainpro_fer.py里的测试集有做tencrop, 可是好像没有fold?我理解的是您将测试集扩大了十倍,然后有十个fold求平均,对fer2013的测试集好像只做了扩大10倍的操作.这里不太懂,不知道是我漏了哪没看,想请教请教您.谢啦~

**Comment by WuJie1010** [comment]
fer2013数据集有testset，不需要做交叉验证，所以不用fold

**Comment by juneweng** [comment]
可是那为什么测试集要tencrop呢 是不是这里tencrop只是为了数据增强呢

**Comment by juneweng** [comment]
或者说十倍交叉验证和测试集变成十倍没有关系呀

**Comment by WuJie1010** [comment]
tencrop只是为了数据增强
