### ISSUE TITLE
do you have non gpu pretrained model 

### ISSUE THREAD

**Issue by shuangshui** [WuJie1010/Facial-Expression-Recognition.Pytorch#40]
Firstly, download the pre-trained model from https://drive.google.com/open?id=1Oy_9YmpkSKX1Q8jkOhJbz3Mc7qjyISzU and then put it in the "FER2013_VGG19" folder; Next, Put the test image (rename as 1.jpg) into the "images" folder, then

I did this on windows pc,bug my computer does not have GPU

**Comment by WuJie1010** [comment]
# 把所有的张量加载到CPU中
torch.load('tensors.pt', map_location=lambda storage, loc: storage)
