### ISSUE TITLE
您的数据划分有问题，并不是subject-independent的。

### ISSUE THREAD

**Issue by ZoieMo** [WuJie1010/Facial-Expression-Recognition.Pytorch#41]
而且您取每一折数据跑出来的最好的准确率来计算最终的准确率，而不是取最后收敛的准确率来计算，是不是不太恰当？

**Comment by WuJie1010** [comment]
一般都是保存最佳模型来计算准确率。

**Comment by ZoieMo** [comment]
这个可以理解。不过数据集划分不是严格subject-independent的，因为每个人的表情图片的数量不一样，所以会有一两折里面训练集和测试集出现相同的人，请问有没有什么方法能够严格划分呢？

**Comment by WuJie1010** [comment]
可能需要手动调整下这个小问题。

**Comment by ZoieMo** [comment]
调整起来比较复杂.....但是直接对118个人进行十折划分，即轮流取106个人的表情图片作为训练集，剩下12个人的表情图片作为测试集，又可能会出现每一折的训练数据和测试数据数量相差比较多的情况....
