### ISSUE TITLE
Windows系统pytorch不再支持py2.7，这个项目怎么跑起来呢？您是在Ubuntu下跑的吗

### ISSUE THREAD

**Issue by lemonmimi** [WuJie1010/Facial-Expression-Recognition.Pytorch#43]

**Comment by WuJie1010** [comment]
您可以用py3的pytorch，改动基本不大，只有极少的py版本的内部改动。

**Comment by zimuyuan** [comment]
作者你好，我尝试在Windows上运行，环境是Win10+PyCharm+python3.7+pytorch1.1，这个过程中有许多问题。现在我运行到python mainpro_FER.py --model VGG19 --bs 128 --lr 0.01 这一步了，但没能成功运行。

正确输出：
VGG19
FER2013
128
0.01
==> Preparing data..
==> Resuming from checkpoint..

Epoch: 124
learning_rate: 0.004304672100000001
错误输出如下：
Traceback (most recent call last):
/Facial-Expression-Recognition.Pytorch-master/mainpro_FER.py", line 236, in <module>
    train(epoch)
  File "F:/深度学习/表情识别-开源案例/表情识别/Facial-Expression-Recognition.Pytorch-master/mainpro_FER.py", line 51, in train
    loss.backward()
  File "D:\Anaconda3\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

就是执行到loss.backward()这个函数是报错了，我刚开始跑代码，这对这很不熟悉，试了一下网上的方法还是没能解决这个错误。你有在windonw下运行过吗？如果有可以给我的帮助或者参考吗。

**Comment by lemonmimi** [comment]
你是不是发错了邮件，我不是这个代码的发布者，你说的这个问题我也不清楚，python3跟2有些语法是不一样的，需要你自己修改一下

**Comment by zimuyuan** [comment]
没有啊，你和作者都可以看到我发的这个问题的，我本来是想问作者的，只是你也能看到。因为看你也提问是Windows所以我就在这问了。那你在Windows成功运行出来了吗？

**Comment by lemonmimi** [comment]
你好，你在windows系统上把这个代码调适通了吗，你现在用的环境是什么呢 ，感谢你的回复
 



------------------ 原始邮件 ------------------
发件人: "zimuyuan"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 下午4:13
收件人: "WuJie1010/Facial-Expression-Recognition.Pytorch"<Facial-Expression-Recognition.Pytorch@noreply.github.com>; 
抄送: "周幂"<1203212378@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [WuJie1010/Facial-Expression-Recognition.Pytorch] Windows系统pytorch不再支持py2.7，这个项目怎么跑起来呢？您是在Ubuntu下跑的吗 (#43)




作者你好，我尝试在Windows上运行，环境是Win10+PyCharm+python3.7+pytorch1.1，这个过程中有许多问题。现在我运行到python mainpro_FER.py --model VGG19 --bs 128 --lr 0.01 这一步了，但没能成功运行。
 
正确输出：
 VGG19
 FER2013
 128
 0.01
 ==> Preparing data..
 ==> Resuming from checkpoint..
 
Epoch: 124
 learning_rate: 0.004304672100000001
 错误输出如下：
 Traceback (most recent call last):
 /Facial-Expression-Recognition.Pytorch-master/mainpro_FER.py", line 236, in 
 train(epoch)
 File "F:/深度学习/表情识别-开源案例/表情识别/Facial-Expression-Recognition.Pytorch-master/mainpro_FER.py", line 51, in train
 loss.backward()
 File "D:\Anaconda3\lib\site-packages\torch\tensor.py", line 107, in backward
 torch.autograd.backward(self, gradient, retain_graph, create_graph)
 File "D:\Anaconda3\lib\site-packages\torch\autograd_init_.py", line 93, in backward
 allow_unreachable=True)  # allow_unreachable flag
 RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
 
就是执行到loss.backward()这个函数是报错了，我刚开始跑代码，这对这很不熟悉，试了一下网上的方法还是没能解决这个错误。你有在windonw下运行过吗？如果有可以给我的帮助或者参考吗。

**Comment by WuJie1010** [comment]
目前没有在window运行过~

**Comment by WuJie1010** [comment]
没有相关论文~
