### ISSUE TITLE
关于准确度和裁剪的问题

### ISSUE THREAD

**Issue by EngeXu** [WuJie1010/Facial-Expression-Recognition.Pytorch#46]
作者你好！非常感谢您分享的代码！有两个问题想请教您。我通过修改网络和超参数将ck准确度提升到了100%，我觉得这是不应该出现的，我认为可能是代码中10折交叉验证中出现了问题（没有将十折的数据轮流使用），或者是我理解的问题？我想的是：作者的test不是传统意义上的test，而只是train中的一部分，是不是应该在之后加上一个测试来检测模型的准确度？
另一个问题，请问在代码中有intraface裁剪出人脸的操作吗？还是只是随机裁剪了图片？谢谢您！

**Comment by WuJie1010** [comment]
交叉验证就是拿一部分数据做训练，再拿剩下部分去做测试~
您出现100%的情况可能是训练和测试样本中有交集部分~
代码没有剪裁人脸的操作，而是拿整个原图来测试~

**Comment by EngeXu** [comment]
谢谢您的解答！真的对我帮助很大！
我看到在运行plot_CK+_confusion_matrix.py后会有多个准确度，是取最后一个accuracy为准嘛？谢谢！

**Comment by lemonmimi** [comment]
你好，请问这个代码实在windows环境下运行的吗，还是其他系统

**Comment by WuJie1010** [comment]
@EngeXu 是的，以最后一个为准

**Comment by WuJie1010** [comment]
@lemonmimi 是在Linux系统，windows也行的·~只是需要切换到py3的版本~

**Comment by EngeXu** [comment]
@WuJie1010 感谢您的细心解答！还有一个让我困惑的是，我在运行您分的fold1出现了100%准确率的情况，我研究学习了下，在fold1中并没有出现训练和测试样本有交集的部分。同时，在这个链接中[https://github.com/HayeonLee/DTAN-ICCV15-pytorch](url)，作者复原了DTAN的论文，在fold3，4，5，6，9中也出现了准确率100%的情况。这种情况是允许存在的嘛？然后您在每个train后接一个test，输出best accuracy，这样做符合要求嘛？谢谢您！
![image](https://user-images.githubusercontent.com/49393901/63830864-ce526480-c99f-11e9-93f3-90b479bf9f27.png)

**Comment by WuJie1010** [comment]
准确率100%在某一些折出现是可能的~证明了你的模型可能训练得很好~

**Comment by EngeXu** [comment]
非常感谢作者！！
