### ISSUE TITLE
resnet18 pre-trained model

### ISSUE THREAD

**Issue by mm4092** [WuJie1010/Facial-Expression-Recognition.Pytorch#5]
Could you provide  pre-trained model of resnet18？

**Comment by WuJie1010** [comment]
We use 10-fold cross validation for the CK+ dataset. There are 10 pre-trained models.

**Comment by mm4092** [comment]
Thanks for your reply，could you share one if possible？ I just want to run the demo.

**Comment by WuJie1010** [comment]
OK! 
https://pan.baidu.com/s/161Rvz25gudQLvXqQwp_QEw 
key：bbpg
