### ISSUE TITLE
1、Can't it run on Windows 10? When I download with win10, tell me the following:

### ISSUE THREAD

**Issue by xingchenbian** [WuJie1010/Facial-Expression-Recognition.Pytorch#54]
1、Can't it run on Windows 10? When I download with win10, tell me the following:
# PyTorch does not support Python 2.7 on Windows. Please install with Python 3.
2、I use win10, python3.7, pytorch2.0, and the error is as follows:
C:\ProgramData\Anaconda3\envs\abc\python.exe C:/Users/Facial-Expression-Recognition.Pytorch-master/preprocess_fer2013.py
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================
General Information:
-------------------
                   HDF5 Version: 1.10.5
                  Configured on: 2019-03-04
                  Configured by: Visual Studio 15 2017 Win64
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/Program Files/HDF5

Compiling Options:
------------------
                     Build Mode: 
              Debugging Symbols: 
                        Asserts: 
                      Profiling: 
             Optimization Level: 

Linking Options:
----------------
                      Libraries: 
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS: 
                     AM_LDFLAGS: 
                Extra libraries: 
                       Archiver: 
                         Ranlib: 

Languages:
----------
                              C: yes
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe 19.16.27027.1
                       CPPFLAGS: 
                    H5_CPPFLAGS: 
                    AM_CPPFLAGS: 
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS: 
                      AM_CFLAGS: 
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:  
                  Fortran Flags: 
               H5 Fortran Flags: 
               AM Fortran Flags: 
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe 19.16.27027.1
                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags: 
                   AM C++ Flags: 
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                   JAVA Compiler:  

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes: 
              Large Parallel I/O: 
              High-level library: ON
                    Threadsafety: OFF
             Default API mapping: v110
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE DECODE ENCODE
                             MPE: 
                      Direct VFD: 
                         dmalloc: 
  Packages w/ extra debug output: 
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
       Strict File Format Checks: OFF
    Optimization Instrumentation: 
Bye...

Process finished with exit code -1073740791 (0xC0000409)
Please tell me how to solve it? Thank you very much.

_Originally posted by @xingchenbian in https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch/issues/50#issuecomment-544402000_

**Comment by WuJie1010** [comment]
h5py codes should change a little bit when switching from python2 to python3.

**Comment by xingchenbian** [comment]
Could you tell me how I should change it?

**Comment by ling1220425528** [comment]
I met the same problem in win10,have you sloved it?

**Comment by ling1220425528** [comment]
I had the same problem on win10,please tell me how to solve it,thanks a lot

**Comment by xingchenbian** [comment]
重新配置一遍就好了，环境的问题，我是重新配置的环境



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ling1220425528"<notifications@github.com&gt;; 
发送时间: 2020年2月7日(星期五) 中午11:42
收件人: "WuJie1010/Facial-Expression-Recognition.Pytorch"<Facial-Expression-Recognition.Pytorch@noreply.github.com&gt;; 
抄送: "星辰"<1522027135@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [WuJie1010/Facial-Expression-Recognition.Pytorch] 1、Can&#39;t it run on Windows 10? When I download with win10, tell me the following: (#54)




I had the same problem on win10,please tell me how to solve it,thanks a lot
