### ISSUE TITLE
Do you have the paper of this project?

### ISSUE THREAD

**Issue by lander1003** [WuJie1010/Facial-Expression-Recognition.Pytorch#56]

**Comment by lander1003** [comment]
有没有这个代码的论文啊，谢谢

**Comment by WuJie1010** [comment]
暂时还没有，但是你可以参考 https://zhuanlan.zhihu.com/p/39779767

**Comment by lander1003** [comment]
好的，谢谢啦，用python3可以吗

**Comment by WuJie1010** [comment]
需要做相应的小改变~

**Comment by NomiMalik0207** [comment]
https://www.mdpi.com/1424-8220/20/4/1087#
you can use this paper as a reference @lander1003
