### ISSUE TITLE
有没有训练好的权重

### ISSUE THREAD

**Issue by 41612237** [WuJie1010/Facial-Expression-Recognition.Pytorch#57]
有没有训练好的权重

**Comment by WuJie1010** [comment]
Download the pre-trained model from https://drive.google.com/open?id=1Oy_9YmpkSKX1Q8jkOhJbz3Mc7qjyISzU (or https://pan.baidu.com/s/1w2TAWzaqh8YvT-1I6rojAg, key:skg2)

**Comment by 41612237** [comment]
Dear WuJie:
&nbsp; &nbsp; Thank you for your sharing.


Sincerely,
Gao liyun




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WuJie"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 上午10:10
收件人:&nbsp;"WuJie1010/Facial-Expression-Recognition.Pytorch"<Facial-Expression-Recognition.Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"高立赟"<376801941@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WuJie1010/Facial-Expression-Recognition.Pytorch] 有没有训练好的权重 (#57)




Download the pre-trained model from https://drive.google.com/open?id=1Oy_9YmpkSKX1Q8jkOhJbz3Mc7qjyISzU (or https://pan.baidu.com/s/1w2TAWzaqh8YvT-1I6rojAg, key:skg2)
