### ISSUE TITLE
h5py objects cannot be pickled

### ISSUE THREAD

**Issue by lander1003** [WuJie1010/Facial-Expression-Recognition.Pytorch#58]
你好，我在运行mainpro_CK+和mainpro_FER两个文件时均出现了h5py objects cannot be pickled这个报错情况，报错语句为这样for batch_idx, (inputs, targets) in enumerate(trainloader):，请问下怎么办啊，万分感谢

**Comment by WuJie1010** [comment]
您是否采用了python3,如果是的话，请按照py3的要求做相应调整

**Comment by lander1003** [comment]
好的，那如果用python2，用pytorch现在最新版本可以吗

**Comment by lander1003** [comment]
现在python2好像安装不了pytorch了，然而python3又不知道咋改，小白表示太难了

**Comment by victor-mageto** [comment]
@lander1003 did you get the solution, am also facing the same error.

**Comment by cimszw** [comment]
try to set 
1. num_workers=0. 
2. datafile = h5py.File(datapath, 'w', swmr=True)
it works for me.

**Comment by victor-mageto** [comment]
where did you define the datapath?

**Comment by lander1003** [comment]
> @lander1003 did you get the solution, am also facing the same error.

I met the error when I use python3, so I change to python2

**Comment by lander1003** [comment]
> @lander1003 @victor-mageto
> It happens because h5py won't read from multiple processes. By omitting num_workers, you're setting it to the default of 0, which uses only the main process. You could also set it to 1 (on Linux, at least).
> So try to set :
> 
> 1. num_workers=0.
> 2. datafile = h5py.File(datapath, 'w', swmr=True)
>    it works for me.

Can have your wechat ID? I really cannot solve it by myself, I'm really new in ML.Thank you!

**Comment by y894577** [comment]
我也是这个问题，有什么办法不回退到python2.7来解决这个问题么

**Comment by lander1003** [comment]
> 我也是这个问题，有什么办法不回退到python2.7来解决这个问题么

我之前就是退回2.7搞得，要是你用python3解决了可以分享一下嘛

**Comment by y894577** [comment]
> > 我也是这个问题，有什么办法不回退到python2.7来解决这个问题么
> 
> 我之前就是退回2.7搞得，要是你用python3解决了可以分享一下嘛

回退2.7会import不了torch，不知道是不是官方抛弃了2.7的问题，python3的代码也不知道从哪改，唉

**Comment by lander1003** [comment]
> > > 我也是这个问题，有什么办法不回退到python2.7来解决这个问题么
> > 
> > 
> > 我之前就是退回2.7搞得，要是你用python3解决了可以分享一下嘛
> 
> 回退2.7会import不了torch，不知道是不是官方抛弃了2.7的问题，python3的代码也不知道从哪改，唉

回退到python2可能需要在linux上才能安装torch老版本了，我记得当时也是这个问题

**Comment by lander1003** [comment]
> > > 我也是这个问题，有什么办法不回退到python2.7来解决这个问题么
> > 
> > 
> > 我之前就是退回2.7搞得，要是你用python3解决了可以分享一下嘛
> 
> 回退2.7会import不了torch，不知道是不是官方抛弃了2.7的问题，python3的代码也不知道从哪改，唉

可以价格wechat交流一下啊

**Comment by y894577** [comment]
> > > > 我也是这个问题，有什么办法不回退到python2.7来解决这个问题么
> > > 
> > > 
> > > 我之前就是退回2.7搞得，要是你用python3解决了可以分享一下嘛
> > 
> > 
> > 回退2.7会import不了torch，不知道是不是官方抛弃了2.7的问题，python3的代码也不知道从哪改，唉
> 
> 可以价格wechat交流一下啊

可以啊，wechat和github同账户名

**Comment by ZangHuanyu** [comment]
> @lander1003 @victor-mageto
> It happens because h5py won't read from multiple processes. By omitting num_workers, you're setting it to the default of 0, which uses only the main process. You could also set it to 1 (on Linux, at least).
> So try to set :
> 
> 1. num_workers=0.
> 2. datafile = h5py.File(datapath, 'w', swmr=True)
>    it works for me.

Could you plz tell me where should I apply "datafile = h5py.File(datapath, 'w', swmr=True)"? Do really appreciated!

**Comment by connorxian** [comment]
> 您是否采用了python3,如果是的话，请按照py3的要求做相应调整
请问是做怎么样的调整呢

**Comment by YELLOWCOOLS** [comment]
datafile = h5py.File(datapath, 'w') ，witch is not used in python3.
You should try use 'pickle' to save data,like this:
"""
train_file=open('data/fer2013/train.txt','wb')
pickle.dump(Training_x,train_file)
"""

**Comment by DaobinZhu** [comment]
代码没有人维护了吗。。我遇到了相同的问题

**Comment by jichongxing2023** [comment]
有解决的吗？最近一直困扰这个问题，有奖解决300RMB，vx：LBJ-2021  急！
