### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by Tony1Q84** [WuJie1010/Facial-Expression-Recognition.Pytorch#6]
when I run the command python visualize.py, I got this error:
Traceback (most recent call last):
  File "visualize.py", line 47, in <module>
    ncrops, c, h, w = np.shape(inputs)
ValueError: need more than 0 values to unpack
Has anyone met this problem?

**Comment by WuJie1010** [comment]
Is the format of the input image correct?

**Comment by Tony1Q84** [comment]
@WuJie1010 Thank you for the answer, I just used the default image, shall I use another image?

**Comment by WuJie1010** [comment]
of course！You may need to cut the region of face before input

**Comment by Tony1Q84** [comment]
@WuJie1010 I follow the step, but it still got same error :(

**Comment by WuJie1010** [comment]
May be the issue caused by the version of Pytorch or torchvision?

**Comment by Tony1Q84** [comment]
@WuJie1010 I justed reinstalled  Pytorch and it worked, thank you so much, may you have a good day!
