### ISSUE TITLE
 device-side assert triggered

### ISSUE THREAD

**Issue by lander1003** [WuJie1010/Facial-Expression-Recognition.Pytorch#60]
File "mainpro_FER.py", line 217, in <module>
    PrivateTest(epoch)
  File "mainpro_FER.py", line 191, in PrivateTest
    correct += predicted.eq(targets.data).cpu().sum()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70
我又遇到新问题了hh，说是标签越界了，但是我也不知道改哪个标签，请问下你当时遇到这个错误了吗

**Comment by WuJie1010** [comment]
没有耶，请好好check你的代码~

**Comment by hzy5660251** [comment]
@lander1003 老哥我也遇到了，请问你解决了吗

**Comment by lander1003** [comment]
> @lander1003 老哥我也遇到了，请问你解决了吗

我之前租了一个服务器跑的，然后出了这个Bug，换了个服务器就好了hhh
