### ISSUE TITLE
Save Model Problem

### ISSUE THREAD

**Issue by DanielXu123** [WuJie1010/Facial-Expression-Recognition.Pytorch#62]
Hi, Wujie.

你好

我想问一下, 网络的输入这里都是需要被resize成 44*44*1 的灰度图像吗?

因为我这边需要尝试将训练的模型保存成onnx格式,但是一直报错好像onnx存储的格式有问题,所以想和你确认下网络的输入

谢谢

**Comment by DanielXu123** [comment]
BTW, 
mainpro_FER.py 文件中的best_PrivateTest_acc_epoch 定义了两个, 第一个应该是手误写错了

**Comment by WuJie1010** [comment]
是的，网络的输入都resize成44*44~

**Comment by DanielXu123** [comment]
> 是的，网络的输入都resize成44*44~

可否再指教一下, 在visualize.py 这个文件中先做resize 48,48 这一步是否是必须做的??

因为现在我训练出来的pth和通过pth转换出来的onnx模型参数对不上, debug发现是因为这一步resize 48*48 导致的. 这一步的目的主要是为了什么呢?
gray = resize(gray, (48,48), mode='symmetric').astype(np.uint8)
既然已经有了
transform_test = transforms.Compose([
    transforms.TenCrop(44),
    transforms.Lambda(lambda crops: torch.stack([transforms.ToTensor()(crop) for crop in crops])),
])

**Comment by WuJie1010** [comment]
> > 是的，网络的输入都resize成44*44~
> 
> 可否再指教一下, 在visualize.py 这个文件中先做resize 48,48 这一步是否是必须做的??
> 
> 因为现在我训练出来的pth和通过pth转换出来的onnx模型参数对不上, debug发现是因为这一步resize 48*48 导致的. 这一步的目的主要是为了什么呢?
> gray = resize(gray, (48,48), mode='symmetric').astype(np.uint8)
> 既然已经有了
> transform_test = transforms.Compose([
> transforms.TenCrop(44),
> transforms.Lambda(lambda crops: torch.stack([transforms.ToTensor()(crop) for crop in crops])),
> ])

您可以尝试下效果~
