### ISSUE TITLE
Training acc

### ISSUE THREAD

**Issue by jcjavaismgood** [WuJie1010/Facial-Expression-Recognition.Pytorch#66]
I retrained the model with my own data, i am surprised to find that model between your profile1-10,1 0th will be better than most of them,and output acc will look bad if sum them uo and average  in confusion_matrix， i wonder the relationship of 10 folder model.        .....appreaciate  your guidance and help !!

**Comment by WuJie1010** [comment]
They are generally independent and have different performance for different samples. So I used the integrated model to improve the accuracy.
