### ISSUE TITLE
Unable to download PrivateTest_model.t7

### ISSUE THREAD

**Issue by NikailaNaidoo** [WuJie1010/Facial-Expression-Recognition.Pytorch#7]
Please may you upload the _PrivateTest_model.t7_ file or provide a username and password for when the Application Baidu downloads. I am trying to download the _PrivateTest_model.t7_ directly from the website given but this is not allowed.

**Comment by NikailaNaidoo** [comment]
nikailanaidoo2@gmail.com
Thank you so much!

**Comment by phamvanlinh143** [comment]
Hello WuJie1010, you can give me your email. I want to get pre-trained model of ResNet18 and VGG16 training on CK+, plz.
