### ISSUE TITLE
关于visualize.py 的一处疑问

### ISSUE THREAD

**Issue by DanielXu123** [WuJie1010/Facial-Expression-Recognition.Pytorch#71]
模型训练得到的精度能达到73%左右, 但是在实测人脸表情数据时, 远远没有达到这个指标,所以就尝试了下降FER2013 的灰度图用来测试, 意在求证模型是否在FER2013 数据集上的精度确实达到了~70%,但是实测还是很糟糕

在使用visualize.py时注意到第57行有一句
`_, predicted = torch.max(outputs_avg.data, 0)`
这里最后的0 应该意思为列, 但是 在mainpro_FER.py 文件中train,PublicTest, PrivateTest 中这个值都是1, 即为行. 这边会是一个导致检测结果不准确的问题点吗?

能否帮忙解释一下这行代码的含义

**Comment by WuJie1010** [comment]
mainpro_FER.py 文件中train,PublicTest, PrivateTest 中这个值都是1，是因为第一维是batch size, visualize.py 已经把数据拿出来求均值了，直接取max得第一维（0）即可。

**Comment by yuhao910716** [comment]
@Hippasuss  问题您解决了么!我也遇到了相同的问题
