### ISSUE TITLE
ImportError: cannot import name 'FER2013' from 'fer'

### ISSUE THREAD

**Issue by HuanyuZang** [WuJie1010/Facial-Expression-Recognition.Pytorch#76]
I got this error below, it was from when I try to import fer after pip install fer in anacondo3 prompt, and got "no module named fer", then I uninstall fer, and pip install fer again in the same way. Then I got this error, and cannot figure out. Any suggestions are appreciated.

ImportError: cannot import name 'FER2013' from 'fer' (C:\Anaconda3\lib\site-packages\fer\__init__.py)

**Comment by WuJie1010** [comment]
FER2013 is imported in https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch/blob/master/fer.py
