### ISSUE TITLE
pytorch cpu版运行报错

### ISSUE THREAD

**Issue by wwzh2015** [WuJie1010/Facial-Expression-Recognition.Pytorch#78]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

怎么改成cpu版本运行

**Comment by WuJie1010** [comment]
please refer to https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch/issues/9

**Comment by upgradwang** [comment]
device = ('cuda' if torch.cuda.is_available() else 'cpu')
use_cuda=device
这样改就改成CPU运行了
