### ISSUE TITLE
How can I test just one image file?

### ISSUE THREAD

**Issue by bemoregt** [WuJie1010/Facial-Expression-Recognition.Pytorch#8]
Hi, @WuJie1010

How can I test just one image file?

I wonder ...

from @bemoregt

**Comment by WuJie1010** [comment]
Firstly, download the pre-trained model from https://pan.baidu.com/s/18cn5sDO4cjPL2G2V4QInOA (key: dgkn) and then put it in the "FER2013_VGG19" folder; Next, Put the test image (rename as 1.jpg) into the "images" folder, then python visualize.py

**Comment by bemoregt** [comment]
Great !

Many Thanks

from @bemoregt

**Comment by bemoregt** [comment]
Hu, @WuJie1010

I can't download that model.

But downloaded strange dmg file. (My O/S :MacOSX)

What;s wrong with me?

**Comment by bemoregt** [comment]
Hi, @WuJie1010 

Thanks, It works.

But the results is something strange ...

![ra](https://user-images.githubusercontent.com/19407972/45585206-b8c56580-b91b-11e8-8f54-48257e0043af.png)

I think that this face looks fear. but the result is neural.

Thanks at any rate~

from @bemoregt
