### ISSUE TITLE
Hi, can i train a binary problem?

### ISSUE THREAD

**Issue by Angel113110** [WuJie1010/Facial-Expression-Recognition.Pytorch#83]
Dear author, thanks for sharing so wonderful work. I have a question to ask you. In my case, I only focus on smile expression. Can I train a binary problem based on your work? Can you give some help or advice? Thanks!

**Comment by WuJie1010** [comment]
In my opinion, you can separate the smile data and other data into two categories. In addition, you should add more neutral facial expressions. You may encounter data imbalance. Remember to use some techniques of data imbalance.
