### ISSUE TITLE
Volatile was removed

### ISSUE THREAD

**Issue by farhanucil** [WuJie1010/Facial-Expression-Recognition.Pytorch#87]
Running mainpro_CK+.py and got this warning:

UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
inputs, targets = Variable(inputs, volatile=True), Variable(targets)

Its located in mainpro_CK+.py line 141, can you give me suggestion? thanks.

**Comment by WuJie1010** [comment]
You may use a higher version of pytorch~ please comment "inputs, targets = Variable(inputs, volatile=True), Variable(targets)", and add "with torch.no_grad():" before eval~
