### ISSUE TITLE
这份代码的loss、acc曲线图如何绘制？

### ISSUE THREAD

**Issue by bai-xi** [WuJie1010/Facial-Expression-Recognition.Pytorch#89]
您好，您方便写一份绘制“这份代码的loss、acc曲线图”的代码吗（FER2013 Dataset）？以便大家参考一下。我是个初学者，还不太会写，改网上其他人绘制loss、acc曲线图的代码不知道从哪下手。

**Comment by ElliotGH** [comment]
可把loss，acc保存下来，用matplotlib画，网上有很多教程的
