### ISSUE TITLE
emmmm

### ISSUE THREAD

**Issue by 2015tdlp** [WuJie1010/Facial-Expression-Recognition.Pytorch#97]
CK+那个我训练了，你的原文件，只是把报的错误改了一下，其他没动，在测试集上的分类准确率只有88%
![test (1)](https://user-images.githubusercontent.com/56304705/88749655-53cd2e80-d186-11ea-9df1-7e4d1c8ad0ce.png)

**Comment by ZangHuanyu** [comment]
测试集博主实现的也只有70出头吧...你怎么这么高

**Comment by SimKarras** [comment]
> 测试集博主实现的也只有70出头吧...你怎么这么高

70那是fer2013
