### ISSUE TITLE
it is overdue to pretrained model downloaded

### ISSUE THREAD

**Issue by eeric** [WuJie1010/Facial-Expression-Recognition.Pytorch#98]
please uploading new link,thanks.

**Comment by WuJie1010** [comment]
Update~
https://pan.baidu.com/s/1gCL0TlCwKctAy_5yhzHy5Q, key: g2d3

**Comment by eeric** [comment]
thanks!

**Comment by Cyrogarb** [comment]
> Update~
> https://pan.baidu.com/s/1gCL0TlCwKctAy_5yhzHy5Q, key: g2d3

can you upload to drive or some other place if it is not too much of a problem.

**Comment by WuJie1010** [comment]
> > Update~
> > https://pan.baidu.com/s/1gCL0TlCwKctAy_5yhzHy5Q, key: g2d3
> 
> can you upload to drive or some other place if it is not too much of a problem.

 https://drive.google.com/open?id=1Oy_9YmpkSKX1Q8jkOhJbz3Mc7qjyISzU
